[project]
directory = "."
sources = ["bug2-func-safe.v"]
toplevel = "lock_on_reset"

[[bugs]]
name = "lock_on_reset_1"
original = "bug2-func-safe.v"
buggy = "bug2-nonfunc.v"

#[[bugs]]
#name = "bug1-func-unsafe"
#original = "./bug1-func-safe.v"
#buggy = "./bug1-func-unsafe.v"

[[testbenches]]
name = "lock_on_reset_tb.v"
sources = ["./tb_bug2.sv"]
output = "test.txt"
oracle = "./test.txt"